# Generated by Django 4.0.2 on 2024-06-02 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('1', 'Maquinista'), ('2', 'Ayudante de Maquinista'), ('3', 'Garrotero')], max_length=1, verbose_name='Género')),
                ('empleado', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=100)),
                ('ingreso', models.DateField(blank=True, null=True, verbose_name='')),
                ('segurosocial', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Trenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmaquina', models.CharField(max_length=100)),
                ('idgps', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('1', 'AGUASCALIENTES'), ('2', 'AJUNO'), ('3', 'CD FRONTERA'), ('4', 'CDMX'), ('5', 'CELAYA'), ('6', 'CHIHUAHUA'), ('7', 'COATZACOALCOS'), ('8', 'CULIACAN'), ('9', 'EL PASO'), ('10', 'GUADALAJARA'), ('11', 'GUAYMAS'), ('12', 'HERMOSILLO'), ('13', 'IRAPUATO'), ('14', 'LOS MOCHIS'), ('15', 'MANZANILLO'), ('16', 'MAZATLAN'), ('17', 'MEXICALI'), ('18', 'MONTERREY'), ('19', 'NACOZARI'), ('20', 'NOGALES'), ('21', 'OJINAGA'), ('22', 'PIEDRAS NEGRAS'), ('23', 'PUEBLA'), ('24', 'RAMOS ARISPE'), ('25', 'SALINA CRUZ'), ('26', 'SALTILLO'), ('27', 'SILAO'), ('28', 'TAMPICO'), ('29', 'TEPIC'), ('30', 'TOPOLOBAMBO'), ('31', 'TORREON'), ('32', 'VERACRUZ'), ('33', 'VERECRUZ'), ('34', 'ZACATECAS')], max_length=2, verbose_name='Origen')),
                ('destino', models.CharField(choices=[('1', 'AGUASCALIENTES'), ('2', 'AJUNO'), ('3', 'CD FRONTERA'), ('4', 'CDMX'), ('5', 'CELAYA'), ('6', 'CHIHUAHUA'), ('7', 'COATZACOALCOS'), ('8', 'CULIACAN'), ('9', 'EL PASO'), ('10', 'GUADALAJARA'), ('11', 'GUAYMAS'), ('12', 'HERMOSILLO'), ('13', 'IRAPUATO'), ('14', 'LOS MOCHIS'), ('15', 'MANZANILLO'), ('16', 'MAZATLAN'), ('17', 'MEXICALI'), ('18', 'MONTERREY'), ('19', 'NACOZARI'), ('20', 'NOGALES'), ('21', 'OJINAGA'), ('22', 'PIEDRAS NEGRAS'), ('23', 'PUEBLA'), ('24', 'RAMOS ARISPE'), ('25', 'SALINA CRUZ'), ('26', 'SALTILLO'), ('27', 'SILAO'), ('28', 'TAMPICO'), ('29', 'TEPIC'), ('30', 'TOPOLOBAMBO'), ('31', 'TORREON'), ('32', 'VERACRUZ'), ('33', 'VERECRUZ'), ('34', 'ZACATECAS')], max_length=2, verbose_name='Destino')),
                ('salida', models.DateField(blank=True, null=True, verbose_name='')),
                ('llegada', models.DateField(blank=True, null=True, verbose_name='')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rutas.trenes', verbose_name='Trenes')),
                ('maquinista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rutas.personal', verbose_name='Personal')),
            ],
        ),
    ]
