# Generated by Django 4.0.2 on 2024-06-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_alter_rutas_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='viaje',
            field=models.TextField(blank=True, null=True, verbose_name='No de viaje'),
        ),
    ]
