# Generated by Django 4.0.2 on 2024-06-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0004_alter_rutas_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutas',
            name='viaje',
        ),
    ]
