# Generated by Django 4.0.2 on 2024-06-02 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0006_rutas_viaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutas',
            old_name='viaje',
            new_name='viajes',
        ),
    ]
