# Generated by Django 4.0.2 on 2024-06-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0007_rename_viaje_rutas_viajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='viajes',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No de viaje'),
        ),
    ]
